[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.8"]
version = ["21.11"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "REDPANDA_VERSION", value = "v21.11.10", if = ["21.11"] },
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[envs.default]
e2e-env = false
